### PR TITLE
Added 2 Algorithms

### PR DESCRIPTION
**Pull request by klvstc**

### CODE REVIEW

**Comment by jmig5776** [comment]
Your programs are of `.cpp` and you had included them in `C` folder. Please migrate them to `C++` folder

**Comment by klvstc** [comment]
The Program are written in C Language using Dev C++. That's why they might have cpp extension but their Language is C.

**Comment by jmig5776** [comment]
Now it good!! Thanks for your so much efforts and lots of algorithms :+1:

**Comment by jmig5776** [comment]
Its merged :+1:

**Pull request merged**
